"""add export downloads

Revision ID: 9d2c6f22f69a
Revises: 2032d24a2842
Create Date: 2026-02-26 18:10:19.416392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2c6f22f69a'
down_revision: Union[str, None] = '2032d24a2842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_downloads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('interest_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('amount_cents', sa.Integer(), server_default='100', nullable=False),
    sa.Column('currency', sa.String(length=8), server_default='USD', nullable=False),
    sa.Column('token', sa.String(length=120), nullable=True),
    sa.Column('token_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_downloads_interest_id'), 'export_downloads', ['interest_id'], unique=False)
    op.create_index(op.f('ix_export_downloads_token'), 'export_downloads', ['token'], unique=True)
    op.create_index(op.f('ix_export_downloads_user_id'), 'export_downloads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_export_downloads_user_id'), table_name='export_downloads')
    op.drop_index(op.f('ix_export_downloads_token'), table_name='export_downloads')
    op.drop_index(op.f('ix_export_downloads_interest_id'), table_name='export_downloads')
    op.drop_table('export_downloads')
    # ### end Alembic commands ###
