"""add interests focus stints pauses

Revision ID: e88c8f0f4fe4
Revises: 952b65dcc7b3
Create Date: 2026-02-26 00:02:27.886352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88c8f0f4fe4'
down_revision: Union[str, None] = '952b65dcc7b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('FOCUS', 'BACKLOG', name='interest_status'), server_default='BACKLOG', nullable=False),
    sa.Column('focus_state', sa.Enum('ACTIVE', 'PAUSED', name='focus_state'), server_default='ACTIVE', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interests_user_id'), 'interests', ['user_id'], unique=False)
    op.create_table('focus_stints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('interest_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=240), nullable=True),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_focus_stints_interest_id'), 'focus_stints', ['interest_id'], unique=False)
    op.create_index(op.f('ix_focus_stints_user_id'), 'focus_stints', ['user_id'], unique=False)
    op.create_table('pause_intervals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stint_id', sa.UUID(), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stint_id'], ['focus_stints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pause_intervals_stint_id'), 'pause_intervals', ['stint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pause_intervals_stint_id'), table_name='pause_intervals')
    op.drop_table('pause_intervals')
    op.drop_index(op.f('ix_focus_stints_user_id'), table_name='focus_stints')
    op.drop_index(op.f('ix_focus_stints_interest_id'), table_name='focus_stints')
    op.drop_table('focus_stints')
    op.drop_index(op.f('ix_interests_user_id'), table_name='interests')
    op.drop_table('interests')
    # ### end Alembic commands ###
